yext/search-headless-react

sample-app/src/components/DecoratedAppliedFilters.tsx, sample-app/src/components/StaticFilters.tsx, sample-app/src/pages/VerticalSearchPage.tsx, sample-app/src/utils/appliedfilterutils.tsx, sample-app/src/utils/displayablefilterutils.tsx
Allow users to specify group labels for applied static filters. `DecoratedAppliedFilters` accepts a mapping of `fieldId` to group label. If no label is provided, it defaults back to using the `fieldId` as the group label.
J=SLAP-1658
TEST=manual
Check that specifying a group label for a static filter fieldId is reflected when a filter with that fieldId is applied
=> Add labels to applied static filters

sample-app/package-lock.json, sample-app/package.json, sample-app/src/components/AlternativeVerticals.tsx, sample-app/src/components/DecoratedAppliedFilters.tsx, sample-app/src/components/Facet.tsx, sample-app/src/components/Facets.tsx, sample-app/src/components/LocationBias.tsx, sample-app/src/components/SearchBar.tsx, sample-app/src/components/StaticFilters.tsx, sample-app/src/components/UniversalResults.tsx, sample-app/src/components/VerticalResults.tsx, sample-app/src/models/cardComponent.ts, sample-app/src/models/displayableFilter.ts, sample-app/src/models/sectionComponent.ts, sample-app/src/utils/appliedfilterutils.tsx, sample-app/src/utils/displayablefilterutils.tsx, sample-app/src/utils/filterutils.tsx, src/AnswersHeadlessProvider.tsx, src/index.ts, tests/components/appliedFilters.test.tsx, tests/useAnswersState.test.tsx
This commit adds an export * from answers-headless statement.
This way, the sample-app doesn't have to use a transient answers-core
or answers-headless dependency for models.
This also makes local development slightly nicer, since transitive dependencies aren't visible
when doing a local npm install.
J=SLAP-1684
TEST=manual
see the sample app runs
=> export * answers-headless

sample-app/package.json
This path does not exist anymore even on my local machine.
J=none
TEST=manual
can do "npm run test"
=> fix testRunner in package.json

.eslintrc.js, package-lock.json, package.json
J=SLAP-1675
TEST=manual
saw eslint notify me if I export an AnswersConfig interface
=> add @yext/export-star eslint usage

sample-app/src/components/FilterSearch.tsx
Found an unexpected behavior in FilterSearch, where all previously selected filter search options persist when a new filterSearch option is selected. Update to ensure that only the current selected filter is applied.
J=none
TEST=manual
in people page, perform multiple filter search and select multiple options, see that only the latest option is applied.
=> FilterSearch: one selected filter

THIRD-PARTY-NOTICES, package-lock.json, package.json
update to use the new version of generate-license-file, which exclude current repo's license in the third-party-notices file
J=SLAP-1754
TEST=manual
ran `npm run generate-notices` with the new version, and see that repo's license is not in the third-party-notices file
=> Update generate license file library

THIRD-PARTY-NOTICES, package-lock.json, package.json, src/AnswersHeadlessProvider.tsx, src/subscribeToStateUpdates.tsx, src/useAnswersState.tsx, tests/useAnswersState.test.tsx, tsconfig.json
Passes the `ANSWERS_HEADLESS_REACT` agent as part of the Client-SDK header to Headless through `provideAnswersHeadless`.
J=SLAP-1951
TEST=manual
Hook up locally to the starter app and see that requests send the Headless React, Headless, and Core agents as part of the Client-SDK header. Requests to the universal search endpoint made for entity previews only send the Headless and Core agents because the hook uses `provideAnswersHeadless` directly to get an instance of Headless instead of going through the `AnswersHeadlessProvider` component from Headless React.
=> Pass Client-SDK agent to Headless

.github/workflows/coverage.yml, .github/workflows/run-tests.yml, .github/workflows/third_party_notices_check.yml
Update the github workflows to use the callable workflows in the `slapshot-reusable-workflows` repo.
J=SLAP-2005
TEST=auto
- See that all three workflows run on this PR as expected.
- Test on another branch (`dev/test-reusable-workflows`) and see that third party notices are updated when needed.
=> Use reusable workflows

THIRD-PARTY-NOTICES, package-lock.json, package.json, src/AnswersHeadlessProvider.tsx, src/useAnswersState.tsx, tests/useAnswersState.test.tsx
This pr updates answers-headless-react to support React 18 as well as 17.
- use alpha version 1.1.1.-alpha.0-95 of answers-headless which contains redux package update to support React 18.
- to support react 18 concurrent mode, useSyncExternalStore is needed. This pr uses `use-sync-external-store` package for backwards-compatible with pre-18 versions (v17).
- ~~From [internal doc](https://github.com/facebook/react/blob/main/packages/use-sync-external-store/src/useSyncExternalStoreShimServer.js#L15)s in `use-sync-external-store`, the package does not offer much logic to support the case of server side rendering for react pre-18 versions. So, this pr update useAnswersState to be conditionally exported with either `useAnswersStateWithManualStoreSync` for SSR pre-18 or …
=> support React 18

.github/workflows/run-tests.yml, package-lock.json, package.json
We support react 16.14 at latest - we do not support earlier versions of 16.
This is due to us using the newest jsx transform which was only added to 16.14 and not earlier versions of 16.
https://reactjs.org/blog/2020/09/22/introducing-the-new-jsx-transform.html
We could make answers-headless-react support earlier versions of react by changing our jsx transform
However in [yext/answers-react-components](https://github.com/yext/answers-react-components) we also depend on restart/ui which requires 16.14. Lastly, we already knew that redux-toolkit requires 16.9, which is another barrier
to support 16.8.
J=SLAP-2113
TEST=manual,auto
hook up local headless-react to local answers-react-components test site using react 16.14
see the components work as expected, and the dev tools say that the …
=> add react 16.14 support to package.json + test different react versions

THIRD-PARTY-NOTICES, package-lock.json, package.json, tests/AnswersHeadlessProvider.test.tsx
Updates answers-headless to the next alpha version which now exports a
SandboxEndpoints object.
J=SLAP-2106
TEST=auto
added test for checking that an answers config is passed from AnswersHeadlessProvider
to provideAnswersHeadless without the endpoints being altered
=> export SandboxEndpoints

.github/workflows/sync_develop_and_main.yml, .github/workflows/version_update.yml
`version_update` and `sync_develop_and_main` workflows were added.
J=SLAP-2159
TEST=manual
Forked this repo, made a release branch and merged into main.  2 PRs were made: one updating for package version and one for merging main into develop.
=> Add official release workflows

README.md, src/subscribeToStateUpdates.tsx
deprecate `subscribeToStateUpdates`. Update README to provide an example for class component to use `AnswersHeadlessContext` directly to dispatch actions and receive updates from state.
J=SLAP-2208
TEST=manual
Test that the new Searcher example with `AnswersHeadlessContext` works as expected. See that README look as expected.
=> deprecate subscribeToStateUpdates

package.json
This PR adds description and keywords to package.json. The description is copied from README and keywords provided by product.
J=SLAP-2190
TEST=manual
=> add description and keywords to package.json

THIRD-PARTY-NOTICES, package-lock.json, package.json
Bump the Headless version to 1.4.0-beta.120 to incorporate the changes in Core to make `Result` a generic.
J=SLAP-2232
TEST=none
=> Update version to 1.4.0-alpha.147

THIRD-PARTY-NOTICES, package-lock.json, package.json
- Updated to the latest version of `search-headless` (v1.4.0) to introduce [new features](https://github.com/yext/search-core/releases/tag/v1.9.0) in `search-core`.
=> Version 1.4.0

THIRD-PARTY-NOTICES, package-lock.json, package.json, tests/setup/server.ts
Had to update the msw mocks to intercept the new search endpoints.
J=None
TEST=manual
unit tests pass again with no errors
before this there would be an "Invalid API Key" error
=> update search-headless to v2 alpha

package-lock.json, package.json
Update all the entry points in package.json to omit the `src` directory. The removal of `package.json` import [here](https://github.com/yext/search-headless-react/pull/156/files#diff-e08419e5b1bb742eaecd92aeeb58a12baa6250e1f1d28d3a35c3bb0f72aa5224L5) means the src/ is no longer generated in the lib folder.
=> Fix build entry path

README.md
update readme wording now that `SearchHeadlessProvider` requires a `SearchHeadless` instance instead of directly passing in the credentials.
=> update readme to reflect SearchHeadlessProvider changes

package-lock.json
Update the version of `@xmldom/xmldom` to address Snyk vulnerabilities in the package.
J=none
TEST=none
=> Address vulnerabilities in `@xmldom/xmldom`

THIRD-PARTY-NOTICES, package-lock.json
Bump the version of `decode-uri-component` to address a Snyk vulnerability in v0.2.0.
J=none
TEST=none
=> Update `decode-uri-component` to fix vulnerability

.github/CODEOWNERS, THIRD-PARTY-NOTICES, package-lock.json, package.json
Prepare v2.2.0 by bumping the version number, and updating the search-headless dependency
=> Prepare v2.2.0

.github/workflows/run-tests.yml, .gitignore, THIRD-PARTY-NOTICES, package-lock.json, package.json, src/SearchHeadlessProvider.tsx, src/useSearchState.tsx, src/useSearchUtilities.ts, tests/SearchHeadlessProvider.test.tsx, tests/useSearchActions.test.tsx, tests/useSearchState.test.tsx, tsconfig.cjs.json, tsconfig.esm.json, tsconfig.json
Introduce tsup and improve the package.json file in order to support PagesJS.
This works in both dev and prod mode of pagesJS
J=BACK-2545
TEST=manual
Publish an alpha version and test it with https://github.com/yext/search-ui-react/pull/400 and @yext/pages@1.0.0-rc.3. Add several search components to the page and confirm they work as expected.
=> PagesJS compatibility

.github/workflows/run-tests.yml, package-lock.json, package.json
Upgrade `@babel/traverse` from v7.16.5 to 7.23.5 to address a critical vulnerability in the package.
J=VULN-38478
TEST=auto
Fix unit tests by pinning `@types/react` to the version that corresponds to the `react` version.
=> Upgrade @babel/traverse

THIRD-PARTY-NOTICES, package-lock.json, package.json
J=CLIP-1226
Update search-core and search-headless versions to 2.6.0-beta which introduce support for Generative Direct Answer
=> update search-headless dependencies version to 2.6.0-beta

THIRD-PARTY-NOTICES, package-lock.json, package.json
New version clears gda state response on error
J=CLIP-1226
TEST=auto
ran `npm run test`
=> update search-headless dependencies version to 2.6.0-beta.2

THIRD-PARTY-NOTICES, package-lock.json, package.json
New version has `queryDurationMillis` as an optional field of VerticalResults
J=CLIP-1226
TEST=auto
ran `npm run test`
=> update search-headless dependencies version to 2.6.0-beta.3

THIRD-PARTY-NOTICES, package-lock.json, package.json
The new beta version has the isPagination variable which upstream beta dependencies of search-headless-react require.
J=none
TEST=auto
ran `npm run test`
=> update search-headless dependencies version to 2.6.0-beta.4

THIRD-PARTY-NOTICES, package-lock.json, package.json
Increase beta version of search-headless (and search-headless-react) to correctly support function vertical.
Test: auto 
ran npm run test and all tests passed.
=> search-headless-react: increase beta version ref of search-headless
