THIRD-PARTY-NOTICES
package-lock.json
package.json
sample-app/package-lock.json

move uuid packages to regular deps instead of dev deps

package update

---

THIRD-PARTY-NOTICES
package-lock.json
package.json
sample-app/package-lock.json
sample-app/package.json

- change sample-app's eslint "error" to "warn". This way compilation doesn't get interrupted
- remove unneeded dep in base package json
- move `@types/` deps to dev deps in base package json
J=None
TEST=manual
sample app runs still

package.json tweaks

---

sample-app/src/components/SearchBar.tsx
sample-app/src/hooks/useSearchWithNearMeHandling.ts
sample-app/src/pages/StandardLayout.tsx

update searchbar to ensure execute right universal/vertical execution
J=none
TEST=manual
see that vertical search page now updates result correctly

Fire the correct search on verticals

---

THIRD-PARTY-NOTICES
package-lock.json
package.json
sample-app/package-lock.json

update version to publish one with all the latest changes for the new sample-app repo
(current beta version is 0.4.1-beta.1)

package version update

---

THIRD-PARTY-NOTICES
package-lock.json
package.json
src/AnswersHeadlessProvider.tsx
tests/useAnswersState.test.tsx

Update answers-headless and answers-headless-react to v0.10.0 and update corresponding tests
J=1757
TEST=manual
Run automated testing, and use this version in the sample app and smoke test

Update headless version to v0.10.0

---

THIRD-PARTY-NOTICES
package-lock.json
package.json

Update version of answers-headless and make new beta version of headless-react.

Update headless version

---

THIRD-PARTY-NOTICES
package-lock.json
package.json

Necessary for source maps to work with create-react-app 5
related: https://github.com/yext/answers-headless/pull/79
J=SLAP-1798
TEST=manual
answers-headless-react works with create-react-app 5

track src in npm package

---

THIRD-PARTY-NOTICES
package-lock.json
package.json

bump version to include changes in[ headless pr](https://github.com/yext/answers-headless/pull/82)
J=SLAP-1906
TEST=none

bump beta version

---

THIRD-PARTY-NOTICES
package-lock.json
package.json

for changes in [this headless pr](https://github.com/yext/answers-headless/pull/83)
J=SLAP-1906
TEST=none

bump to v1.1.0-beta.6

---

THIRD-PARTY-NOTICES
package-lock.json
package.json

1.1.1-alpha.123

---

THIRD-PARTY-NOTICES
package-lock.json
package.json

Update the Headless version to v1.2.0

Update version to 1.2.0

---

LICENSE
package-lock.json
package.json
tests/useAnswersState.test.tsx
tests/utils/acquireSessionId.test.ts

Addresses 2 minor styling issues.
J=SLAP-2135
TEST=none

update eslint-config-slapshot to 0.4.0

---

LICENSE
THIRD-PARTY-NOTICES
package-lock.json
package.json
src/SearchHeadlessContext.ts
src/SearchHeadlessProvider.tsx
src/deprecated.ts
src/index.ts
src/subscribeToStateUpdates.tsx
src/useSearchActions.ts
src/useSearchState.tsx
src/useSearchUtilities.ts
tests/SearchHeadlessProvider.test.tsx
tests/useSearchState.test.tsx

replaced all `answers-headless` imports with `search-headless` counterparts. also updated `package.json` version
J=SLAP-2196
TEST=auto

Answers -> Search 2: rename imports

---

THIRD-PARTY-NOTICES
package-lock.json
package.json

update headless version for direct answer related changes

update headless version for DA changes

---

package-lock.json

Upgrade `nwsapi` to v2.2.2 to address a vulnerability in v2.2.0.
J=none
TEST=none

Upgrade `nwsapi` to address vulnerability

---

.gitignore
THIRD-PARTY-NOTICES
package-lock.json
package.json

Bump @yext/search-headless to Version 2.2.1-beta.0
Also bump @yext/search-headless-react to 2.2.0-beta.0.
J=BACK-2270
TEST=auto
Ran `npm run test`.

Bump @yext/search-headless to Version 2.2.1-beta.0

---

package.json

forgot to change the version number of the actual package in the previous PR

bump the version number of the actual package

---

THIRD-PARTY-NOTICES
package-lock.json
package.json

Update package.json version and bump search-headless version to 2.4.0

Prepare v2.3.0

---

THIRD-PARTY-NOTICES
package-lock.json
package.json

Bump search-core and search-headless versions to 2.4.0 which introduce support for Markdown, RichText_v2 (Lexical), and HTML featured snippets

Version 2.3.0

---

THIRD-PARTY-NOTICES
package-lock.json
package.json

Add document vertical support by bumping the search-headless version
J=BACK-2523
TEST=manual
Manually tested that I can load the segment result

Document vertical support

---

THIRD-PARTY-NOTICES
package-lock.json
package.json

Bump the search headless beta version in order to revert the rawData breaking change
J=BACK-2523
TEST=compile

v2.4.0 beta.3

---

package-lock.json
package.json

This PR upgrades multiple packages in the repo which have VULNs.
J=VULN-38478,39486,39485
TEST=compile

ksearch: update dependencies for vulns

---

THIRD-PARTY-NOTICES
package-lock.json
package.json

Bumps search-headless version to include change that added optional name property for near field value filters.

Add name property for near field value filters
